# Generated by Django 4.1.3 on 2023-01-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISPL_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='team',
            field=models.ManyToManyField(to='ISPL_app.team'),
        ),
    ]
